import Foundation

/// The decoded form of `datagrep_catalog_describe_json`.
///
/// **Everything here is optional on purpose.** Three different producers already
/// answer this call with three different payloads:
///
/// * the C stub — `{name, kind, columns:[{name,type,nullable}], primary_key:[…], approx_rows}`
/// * `datagrep-ffi` today — `{path, name, kind, comment, columns:[{name,type,native_type,
///   nullable,primary_key,unique,auto_generated,indexed}] | null, extra:[[k,v],…]}`
/// * `datagrep-ffi` in progress — the above plus `default`, `ordinal`, `logical_type`,
///   an `indexes` array, object stats, and `inferred`/`sampled_docs` for Mongo.
///
/// So this decoder never uses `Codable`: it walks untyped JSON, accepts every
/// spelling of a field it has seen or been promised, coerces numbers that
/// arrive as strings (Mongo's `extra` stringifies everything), and drops what
/// it cannot read instead of failing. A missing key is rendered as absent, and
/// absent is a fact the pane is allowed to state — it is never a crash and
/// never a blank pane.
public struct SchemaDetail: Sendable {
    public var name: String
    public var kind: String
    public var path: [String]
    public var comment: String?

    /// `nil` means *this engine declares no schema* — a different fact from
    /// "declared, and has no columns", which is `[]`. Redis and a Mongo
    /// database both land on `nil`.
    public var columns: [SchemaColumn]?

    /// Empty when the payload carried an `indexes` key with nothing in it, and
    /// also when it carried no such key at all — `indexesReported` separates
    /// the two so the pane can say "none" instead of implying none.
    public var indexes: [SchemaIndex]
    public var indexesReported: Bool

    public var rowEstimate: Int64?
    public var sizeBytes: Int64?
    public var sizeLabel: String?

    /// Mongo (and the SQLite key/value shim) build the field list by sampling
    /// documents. Presenting that as a declared schema would be a lie, so it
    /// is carried separately and always labelled.
    public var inferred: Bool
    public var sampledDocs: Int64?

    /// `CREATE TABLE …` if the backend hands one over. Never synthesised here.
    public var definition: String?

    /// Whatever else the driver attached, minus the keys promoted above.
    /// Redis's entire answer is in here (`type`, `ttl`, `object_encoding`, …).
    public var extra: [(key: String, value: String)]

    /// The payload, pretty-printed, for "copy raw JSON" and for the escape
    /// hatch when the pane cannot make sense of a new field yet.
    public var rawJSON: String

    public var columnCount: Int? { columns?.count }
    public var primaryKeyColumns: [String] { (columns ?? []).filter(\.isPrimaryKey).map(\.name) }
}

public struct SchemaColumn: Sendable, Identifiable, Hashable {
    public var id: Int
    public var name: String
    /// Engine spelling (`varchar(64)`, `timestamptz`) when the driver has one.
    public var nativeType: String?
    /// datagrep's `LogicalType` — always a fallback, never a replacement, because
    /// `Utf8` tells a DBA less than `varchar(64)` does.
    public var logicalType: String?
    public var nullable: Bool?
    public var defaultValue: String?
    public var isPrimaryKey: Bool
    public var isUnique: Bool
    public var isIndexed: Bool
    public var isAutoGenerated: Bool
    public var ordinal: Int?
    /// Mongo only: the share of sampled documents the field was present in.
    public var presence: Double?

    /// What the type column shows. Native first, logical second, `?` when the
    /// driver declared neither — an unknown type is stated, not blanked.
    public var displayType: String {
        if let n = nativeType, !n.isEmpty { return n }
        if let l = logicalType, !l.isEmpty { return l }
        return "?"
    }

    /// `native · Logical` when both exist and disagree — the tooltip, not the row.
    public var typeDetail: String? {
        guard let l = logicalType, !l.isEmpty else { return nil }
        guard let n = nativeType, !n.isEmpty, n.caseInsensitiveCompare(l) != .orderedSame else {
            return nil
        }
        return l
    }
}

public struct SchemaIndexKey: Sendable, Hashable {
    public var name: String
    /// `nil` when the driver did not say — an index on a hash or a GIN index
    /// has no meaningful direction, and inventing `ASC` would be wrong.
    public var descending: Bool?
    public var arrow: String? {
        guard let descending else { return nil }
        return descending ? "↓" : "↑"
    }
}

public struct SchemaIndex: Sendable, Identifiable {
    public var id: Int
    public var name: String
    public var keys: [SchemaIndexKey]
    public var isUnique: Bool
    public var isPrimary: Bool
    /// `btree`, `hash`, `2dsphere`, … whatever the engine calls it.
    public var type: String?
    /// The partial-index predicate, when the engine exposes it.
    public var partial: String?
    public var ttlSeconds: Int64?

    public var keyLine: String {
        keys.map { k in k.arrow.map { "\(k.name) \($0)" } ?? k.name }
            .joined(separator: ", ")
    }
}

// MARK: - decoding

extension SchemaDetail {
    /// Never throws and never returns `nil` for a payload that is *some* kind of
    /// JSON object. Only genuinely unparseable text fails, and the caller shows
    /// that as an error rather than an empty schema.
    public static func decode(_ json: String, fallbackName: String, fallbackKind: String)
        -> SchemaDetail?
    {
        guard let root = jsonObject(json) as? [String: Any] else { return nil }
        let extraPairs = J.pairs(root["extra"])
        // Extras are searched with the same aliasing as the top level, because
        // the current FFI puts stats in `extra` and the next one promotes them.
        let bag = Bag(root: root, extra: extraPairs)

        let declaredColumns = decodeColumns(root)
        let (indexes, reported) = decodeIndexes(root)

        // The stub spells the primary key as a top-level `["id"]` list rather
        // than a per-column flag. Fold it in so the key glyph appears there too.
        var columns = declaredColumns
        let pkNames = Set(J.strings(root["primary_key"] ?? root["primary_keys"]))
        if !pkNames.isEmpty, columns != nil {
            for i in columns!.indices where pkNames.contains(columns![i].name) {
                columns![i].isPrimaryKey = true
            }
        }
        // An index flagged `primary` is the same statement by another route.
        if columns != nil, let pk = indexes.first(where: { $0.isPrimary }) {
            let names = Set(pk.keys.map(\.name))
            for i in columns!.indices where names.contains(columns![i].name) {
                columns![i].isPrimaryKey = true
            }
        }

        let promoted: Set<String> = [
            "inferred_schema", "inferred", "sampled_docs", "sampled", "sample_size",
            "document_count", "row_estimate", "approx_rows", "rows", "row_count",
            "estimated_rows", "size_bytes", "storage_size_bytes", "total_size_bytes",
        ]

        return SchemaDetail(
            name: J.string(root["name"]) ?? fallbackName,
            kind: J.string(root["kind"]) ?? fallbackKind,
            path: J.strings(root["path"]),
            comment: J.string(root["comment"]),
            columns: columns,
            indexes: indexes,
            indexesReported: reported,
            rowEstimate: bag.int([
                "row_estimate", "approx_rows", "rows", "row_count", "estimated_rows",
                "document_count", "count",
            ]),
            sizeBytes: bag.int([
                "size_bytes", "storage_size_bytes", "total_size_bytes", "bytes",
                "memory_bytes", "size",
            ]),
            // Only keys that are pre-formatted *for a human*. `total_size` is
            // deliberately absent: Postgres spells that in raw bytes, and
            // printing "81920" where "80 KB" belongs is worse than no label.
            sizeLabel: bag.string(["size_pretty", "size_human"]),
            inferred: bag.bool(["inferred", "inferred_schema", "schema_inferred", "is_inferred"])
                ?? false,
            sampledDocs: bag.int(["sampled_docs", "sampled", "sample_size", "sampled_documents"]),
            definition: bag.string(["definition", "ddl", "create_statement", "sql", "view_definition"]),
            extra: extraPairs.filter { !promoted.contains($0.key.lowercased()) },
            rawJSON: prettyJSON(json) ?? json)
    }

    private static func decodeColumns(_ root: [String: Any]) -> [SchemaColumn]? {
        // `"columns": null` is load-bearing: the FFI writes it to mean "this
        // engine declares no schema at all". Only a present array is a schema.
        var raw = root["columns"] ?? root["fields"] ?? root["schema"]
        // `"schema": {"fields": [...]}` — the shape `RowSchema` would serialise to
        // if the FFI ever stopped hand-flattening it.
        if let wrapper = raw as? [String: Any] { raw = wrapper["fields"] ?? wrapper["columns"] }
        guard let arr = raw as? [Any] else { return nil }
        return arr.enumerated().compactMap { idx, item -> SchemaColumn? in
            // A bare `["id", "name"]` column list is legal input too.
            if let name = item as? String {
                return SchemaColumn(
                    id: idx, name: name, nativeType: nil, logicalType: nil, nullable: nil,
                    defaultValue: nil, isPrimaryKey: false, isUnique: false, isIndexed: false,
                    isAutoGenerated: false, ordinal: idx, presence: nil)
            }
            guard let d = item as? [String: Any] else { return nil }
            guard let name = J.string(d["name"] ?? d["column"] ?? d["field"]) else { return nil }
            // `type` means the native spelling in the stub and the logical one
            // in the FFI, so it is only used where the specific key is absent.
            let native = J.string(d["native_type"] ?? d["native"] ?? d["data_type"])
            let logical = J.string(d["logical_type"] ?? d["logical"])
            let loose = J.string(d["type"])
            return SchemaColumn(
                id: idx,
                name: name,
                nativeType: native ?? (logical == nil ? loose : nil),
                logicalType: logical ?? (native != nil ? loose : nil),
                nullable: J.bool(d["nullable"] ?? d["is_nullable"] ?? d["null"]),
                defaultValue: J.looseString(d["default"] ?? d["default_value"] ?? d["column_default"]),
                isPrimaryKey: J.bool(d["primary_key"] ?? d["is_primary_key"] ?? d["pk"]) ?? false,
                isUnique: J.bool(d["unique"] ?? d["is_unique"]) ?? false,
                isIndexed: J.bool(d["indexed"] ?? d["is_indexed"]) ?? false,
                isAutoGenerated: J.bool(
                    d["auto_generated"] ?? d["auto_increment"] ?? d["generated"]) ?? false,
                ordinal: J.int(d["ordinal"] ?? d["ordinal_position"] ?? d["position"]).map(Int.init)
                    ?? idx,
                presence: J.double(d["presence_ratio"] ?? d["presence"]))
        }
        .sorted { ($0.ordinal ?? $0.id) < ($1.ordinal ?? $1.id) }
    }

    private static func decodeIndexes(_ root: [String: Any]) -> ([SchemaIndex], Bool) {
        let raw = root["indexes"] ?? root["index"]
        // Not an array — including an explicit `null` — means the driver did
        // not report indexes. The pane says "not reported", not "none".
        guard let arr = raw as? [Any] else { return ([], false) }
        let list = arr.enumerated().compactMap { idx, item -> SchemaIndex? in
            if let name = item as? String {
                return SchemaIndex(
                    id: idx, name: name, keys: [], isUnique: false, isPrimary: false, type: nil,
                    partial: nil, ttlSeconds: nil)
            }
            guard let d = item as? [String: Any] else { return nil }
            let name = J.string(d["name"] ?? d["index"]) ?? "index \(idx + 1)"
            let partial: String? = {
                if let s = J.string(d["partial_filter"] ?? d["filter"] ?? d["where"] ?? d["condition"]) {
                    return s
                }
                // `"partial": true` with no predicate still deserves the badge.
                return (J.bool(d["partial"] ?? d["is_partial"]) ?? false) ? "" : nil
            }()
            return SchemaIndex(
                id: idx,
                name: name,
                keys: decodeIndexKeys(d["keys"] ?? d["columns"] ?? d["fields"] ?? d["key"]),
                isUnique: J.bool(d["unique"] ?? d["is_unique"]) ?? false,
                isPrimary: J.bool(d["primary"] ?? d["is_primary"]) ?? false,
                type: J.string(d["type"] ?? d["method"] ?? d["kind"] ?? d["using"]),
                partial: partial,
                ttlSeconds: J.int(
                    d["ttl"] ?? d["ttl_seconds"] ?? d["expire_after_seconds"]
                        ?? d["expireAfterSeconds"]))
        }
        return (list, true)
    }

    /// Keys arrive as `["a","b"]`, as `[{"name":"a","direction":"desc"}]`, as
    /// `[{"field":"a","order":-1}]` (Mongo's own spelling), or as a single
    /// string. All four land here.
    private static func decodeIndexKeys(_ raw: Any?) -> [SchemaIndexKey] {
        if let s = raw as? String { return [SchemaIndexKey(name: s, descending: nil)] }
        if let d = raw as? [String: Any] {
            // `{"created_at": -1, "user_id": 1}` — a Mongo key document.
            return d.map { k, v in SchemaIndexKey(name: k, descending: directionIsDescending(v)) }
                .sorted { $0.name < $1.name }
        }
        guard let arr = raw as? [Any] else { return [] }
        return arr.compactMap { item in
            if let s = item as? String { return SchemaIndexKey(name: s, descending: nil) }
            guard let d = item as? [String: Any] else { return nil }
            guard let name = J.string(d["name"] ?? d["column"] ?? d["field"] ?? d["key"]) else {
                return nil
            }
            let dir =
                d["direction"] ?? d["order"] ?? d["descending"] ?? d["desc"] ?? d["sort"]
            return SchemaIndexKey(name: name, descending: directionIsDescending(dir))
        }
    }

    /// `-1`, `"desc"`, `"DESC"`, `"descending"` and `true` all mean the same
    /// thing; anything unrecognised means "the driver did not say".
    private static func directionIsDescending(_ v: Any?) -> Bool? {
        guard let v, !(v is NSNull) else { return nil }
        // Order matters: Mongo writes `1`/`-1`, and Swift bridges NSNumber(1)
        // to `Bool` happily, so a real boolean has to be identified as a
        // CFBoolean first or `1` (ascending) would decode as `true` (descending).
        if let b = J.rawBool(v) { return b }
        if let n = J.int(v) { return n < 0 ? true : (n > 0 ? false : nil) }
        guard let s = J.string(v)?.lowercased() else { return nil }
        if s.hasPrefix("desc") || s == "-1" || s == "↓" { return true }
        if s.hasPrefix("asc") || s == "1" || s == "↑" { return false }
        return nil
    }

    static func prettyJSON(_ text: String) -> String? {
        guard let data = text.data(using: .utf8),
            let obj = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]),
            let out = try? JSONSerialization.data(
                withJSONObject: obj, options: [.prettyPrinted, .sortedKeys, .fragmentsAllowed])
        else { return nil }
        return String(data: out, encoding: .utf8)
    }
}

/// Looks a key up at the top level first, then in `extra`, trying every alias
/// in order. This is the whole reason a stat can move from `extra` into the
/// root of the payload without breaking the pane.
private struct Bag {
    let root: [String: Any]
    let extra: [(key: String, value: String)]

    private func find(_ keys: [String]) -> Any? {
        for k in keys {
            if let v = root[k], !(v is NSNull) { return v }
        }
        for k in keys {
            if let hit = extra.first(where: { $0.key.caseInsensitiveCompare(k) == .orderedSame }) {
                return hit.value
            }
        }
        return nil
    }

    func int(_ keys: [String]) -> Int64? { J.int(find(keys)) }
    func string(_ keys: [String]) -> String? {
        guard let s = J.string(find(keys)), !s.isEmpty else { return nil }
        return s
    }
    func bool(_ keys: [String]) -> Bool? { J.bool(find(keys)) }
}

/// Coercions. Mongo stringifies every number it puts in `extra`, and a JSON
/// bool can arrive as `"true"` through the same door, so nothing here trusts
/// the static type it was handed.
private enum J {
    /// True only for a JSON `true`/`false`. `v as? Bool` is not good enough:
    /// Swift bridges `NSNumber(0)` and `NSNumber(1)` to `Bool` as well, which
    /// silently turns a Mongo sort direction into a flag.
    static func rawBool(_ v: Any?) -> Bool? {
        guard let v, !(v is NSNull) else { return nil }
        guard CFGetTypeID(v as CFTypeRef) == CFBooleanGetTypeID() else { return nil }
        return (v as? NSNumber)?.boolValue
    }

    static func string(_ v: Any?) -> String? {
        guard let v, !(v is NSNull) else { return nil }
        if let s = v as? String { return s }
        if let b = rawBool(v) { return b ? "true" : "false" }
        if let n = v as? NSNumber { return n.stringValue }
        return nil
    }

    /// For `default`, where `0`, `false` and `"now()"` are all real values and
    /// the difference between them matters to the reader.
    static func looseString(_ v: Any?) -> String? {
        guard let v, !(v is NSNull) else { return nil }
        if let s = v as? String { return s.isEmpty ? nil : s }
        if let b = rawBool(v) { return b ? "true" : "false" }
        if let n = v as? NSNumber { return n.stringValue }
        return nil
    }

    static func int(_ v: Any?) -> Int64? {
        guard let v, !(v is NSNull) else { return nil }
        if let n = v as? NSNumber { return n.int64Value }
        if let s = v as? String {
            if let i = Int64(s.trimmingCharacters(in: .whitespaces)) { return i }
            if let d = Double(s.trimmingCharacters(in: .whitespaces)) { return Int64(d) }
        }
        return nil
    }

    static func double(_ v: Any?) -> Double? {
        guard let v, !(v is NSNull) else { return nil }
        if let n = v as? NSNumber { return n.doubleValue }
        if let s = v as? String { return Double(s) }
        return nil
    }

    static func bool(_ v: Any?) -> Bool? {
        guard let v, !(v is NSNull) else { return nil }
        if let b = rawBool(v) { return b }
        if let n = v as? NSNumber { return n.boolValue }
        guard let s = (v as? String)?.lowercased() else { return nil }
        if ["true", "yes", "1", "t"].contains(s) { return true }
        if ["false", "no", "0", "f"].contains(s) { return false }
        return nil
    }

    static func strings(_ v: Any?) -> [String] {
        guard let arr = v as? [Any] else { return [] }
        return arr.compactMap { string($0) }
    }

    /// `extra` is `[[k, v], …]` today and could reasonably become `{k: v}`.
    static func pairs(_ v: Any?) -> [(key: String, value: String)] {
        if let arr = v as? [Any] {
            return arr.compactMap { item in
                if let pair = item as? [Any], pair.count >= 2,
                    let k = string(pair[0]), let val = looseString(pair[1]) ?? string(pair[1])
                {
                    return (k, val)
                }
                if let d = item as? [String: Any], let k = string(d["key"] ?? d["name"]),
                    let val = looseString(d["value"])
                {
                    return (k, val)
                }
                return nil
            }
        }
        if let d = v as? [String: Any] {
            return d.compactMap { k, val in looseString(val).map { (k, $0) } }
                .sorted { $0.0 < $1.0 }
        }
        return []
    }
}

// MARK: - formatting helpers shared by the pane

extension SchemaDetail {
    public static func formatBytes(_ bytes: Int64) -> String {
        let f = ByteCountFormatter()
        f.countStyle = .file
        f.allowedUnits = [.useKB, .useMB, .useGB, .useTB]
        return f.string(fromByteCount: bytes)
    }

    public static func formatCount(_ n: Int64) -> String {
        n.formatted(.number.grouping(.automatic))
    }
}

/// Turning a schema back into text you can paste. Lives beside the decoder
/// rather than in the view because it is pure data work, and because it is the
/// part of a schema pane people use most.
public enum SchemaClipboard {
    public static func names(_ d: SchemaDetail) -> String {
        (d.columns ?? []).map(\.name).joined(separator: "\n")
    }

    public static func namesAndTypes(_ d: SchemaDetail) -> String {
        let cols = d.columns ?? []
        let width = cols.map(\.name.count).max() ?? 0
        return cols.map { c in
            c.name.padding(toLength: max(width, c.name.count), withPad: " ", startingAt: 0)
                + "  " + c.displayType
        }
        .joined(separator: "\n")
    }

    public static func selectList(_ d: SchemaDetail) -> String {
        (d.columns ?? []).map(\.name).joined(separator: ", ")
    }

    /// Only offered when the engine declared the schema. An inferred field list
    /// is not a table definition, and dressing one up as `CREATE TABLE` would
    /// be exactly the kind of confident-sounding wrong answer this app avoids.
    public static func generatedDDL(_ d: SchemaDetail) -> String? {
        guard !d.inferred, let cols = d.columns, !cols.isEmpty else { return nil }
        // A column whose type the driver never reported cannot appear in a
        // CREATE statement, and `id ?` is not a definition — it is a guess with
        // punctuation. No types, no offer.
        guard cols.allSatisfy({ $0.displayType != "?" }) else { return nil }
        let table = d.path.isEmpty ? d.name : d.path.suffix(2).joined(separator: ".")
        var lines = cols.map { c -> String in
            var line = "  \(c.name) \(c.displayType)"
            if c.nullable == false { line += " NOT NULL" }
            if let def = c.defaultValue { line += " DEFAULT \(def)" }
            return line
        }
        let pk = d.primaryKeyColumns
        if !pk.isEmpty { lines.append("  PRIMARY KEY (\(pk.joined(separator: ", ")))") }
        return "-- generated by datagrep from describe(); not read back from the engine\n"
            + "CREATE TABLE \(table) (\n" + lines.joined(separator: ",\n") + "\n);"
    }
}
